### ISSUE TITLE
Spring Boot 1.4 error on java build pack

### ISSUE THREAD

**Issue by sergiubodiu** [vmware-archive/pcfdev#119]
Hi,

I'm getting an error on PCF dev when pushing a spring boot app with mysql to pcfdev:

 ~/Downloads/demo cf dev version
PCF Dev version 0.19.0 (CLI: 27d4cda, OVA: 0.234.0)

https://github.com/sergiubodiu/spring-boot-pcfdev

 2016-08-09T05:26:50.18+0800 [APP/0]      ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.lang.reflect.Method.invoke(Method.java:497)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:422)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:401)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:392)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:261)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:237)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at com.example.DemoApplication.main(DemoApplication.java:19)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    ... 8 more
2016-08-09T05:26:50.18+0800 [APP/0]      ERR Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextInitializer
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.lang.ClassLoader.defineClass1(Native Method)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.security.AccessController.doPrivileged(Native Method)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:414)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    ... 15 more
2016-08-09T05:26:50.18+0800 [APP/0]      ERR Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContextInitializer
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-08-09T05:26:50.18+0800 [APP/0]      ERR    ... 31 more
2016-08-09T05:26:50.21+0800 [APP/0]      OUT Exit status 1

However the issue disappears if I'm pushing to PWS or using latest java build pack:
cf push -b https://github.com/cloudfoundry/java-buildpack.git

**Comment by ekcasey** [comment]
@sergiubodiu,

The next release of pcfdev should update the java buildpack to v3.8.1. Does that version work for you?

**Comment by sergiubodiu** [comment]
@ekcasey, 
yes this should solve the problem

**Comment by mdelillo** [comment]
Ok, that release should come out in the next few weeks. Feel free to re-open this if you are still having issues with it.
