### ISSUE TITLE
Gradle Donwload

### ISSUE THREAD

**Issue by chorode** [vmware-archive/pcfdev#216]
One of the steps in deploying the sample Java app is assembling the app locally using Gradle.  
Is there a way to specify to use the already installed instance of gradle rather than for the script to go and download Gradle again?

 I am behind a proxy on a corporate network which i believe is causing the gradle download to fail. Configuring HTTP_PROXY or HTTPS_PROXY has not helped either. 

I have gradle 2.14 installed on my box. So, is there was a way to get to use the already installed instance of Gradle rather than to go and download Gradle.

C:\Downloads\spring-music-master\spring-music-master>.\gradlew.bat assemble

Downloading https://services.gradle.org/distributions/gradle-2.14-bin.zip

Exception in thread "main" java.net.ConnectException: Connection refused: connect
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:529)
        at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:564)
        at com.sun.net.ssl.internal.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:141)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:163)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:395)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:530)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:272)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:329)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:172)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:911)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:158)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1172)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by sclevine** [comment]
Can you try setting `http_proxy` and `https_proxy` instead? Many applications only respect the lower-cased versions.

I suspect that you will need an internet connection to build that sample app.

**Comment by chorode** [comment]
i do have an internet connection and can access https://services.gradle.org/distributions/gradle-2.14-bin.zip from a browser.

**Comment by chorode** [comment]
Also, i forgot to mention that the lower case http/s_proxy environment variables did not make any difference.

Going back to the original question do i take that there is no way to use the existing Gradle set up and the only option is to download Gradle.

**Comment by sclevine** [comment]
On my machine, the gradle zip is downloaded to:
```
~/.gradle/wrapper/dists/gradle-2.14-bin/76oc0mnc3ieqtsukq90mp0rxk/gradle-2.14-bin.zip
```
And it's not downloaded again on subsequent builds. You may be able to download it separately and provide it to gradle -- I'm not really sure, I don't use gradle. Regardless, you still won't be able to build spring-music without HTTP connectivity, because gradle needs to download 100+ other Java dependencies to build it.

This issue tracker is for questions about PCF Dev -- I suggest you refer to the gradle documentation for questions about gradle: https://gradle.org/docs
