### ISSUE TITLE
Custom PCFDEV OVA build fails due to Provisioning deployment error

### ISSUE THREAD

**Issue by antonioaguilar** [vmware-archive/pcfdev#332]
I was trying to build a custom PCFDEV OVA with `./bin/build -only=virtualbox-ovf` but ran into the following issue:

```
    virtualbox-ovf: Started configuring bosh agent > Configuring infrastructure settings
    virtualbox-ovf: Finished configuring bosh agent > Configuring infrastructure settings
    virtualbox-ovf: Started setting up instance pcfdev/0 > Applying

    virtualbox-ovf: Failed setting up instance pcfdev/0 > Applying
    virtualbox-ovf:
    virtualbox-ovf: -----
    virtualbox-ovf: Error: Provisioning deployment: Starting instance: Updating instance 0: Applying: Compiling templates pcfdev: Compiling templates: Rendering config/cloud_controller_ng.yml ERB: Running ruby: Running command: 'ruby /tmp/erb-render.rb /tmp/erb-context.json /opt/bosh-provisioner/tmp/tar-CmdExtractor552926110/templates/cloud_controller_clock.yml.erb /opt/bosh-provisioner/tmp/instance-templatescompiler-RenderedArchivesCompiler250718899/cloud_controller_clock/config/cloud_controller_ng.yml', stdout: '', stderr: '/tmp/erb-render.rb:151:in `rescue in render': Error filling in template '/opt/bosh-provisioner/tmp/tar-CmdExtractor552926110/templates/cloud_controller_clock.yml.erb' for pcfdev/0 (line 150: #<TemplateEvaluationContext::UnknownProperty: Can't find property '["build"]'>) (RuntimeError)
    virtualbox-ovf: from /tmp/erb-render.rb:137:in `render'
    virtualbox-ovf: from /tmp/erb-render.rb:162:in `<main>'
    virtualbox-ovf: ': exit status 1
    virtualbox-ovf: -----
==> virtualbox-ovf: Executing provisioner: Non-zero exit status: 1
```
There seems to be an issue with the `bosh-provisioner` ... 

Any ideas how to overcome this?

thanks, 

A.

**Comment by antonioaguilar** [comment]
Do you have an update on this issue?

**Comment by sclevine** [comment]
Sorry for the delay. The code in this repo is no longer maintained. PCF Dev is now based on CF Dev: https://github.com/cloudfoundry-incubator/cfdev
