### ISSUE TITLE
Error starting cf-mysql-broker 

### ISSUE THREAD

**Issue by geoffwa** [vmware-archive/pcfdev#35]
We're running the latest nightly build - micropcf-v0.6.0-18-g0b99532 and seeing the following error starting the broker:

`````` shell
mysql_broker already exists


rake aborted!
JSON::ParserError: 776: unexpected token at '<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/json_pure-1.8.2/lib/json/common.rb:155:in `parse'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/json_pure-1.8.2/lib/json/common.rb:155:in `parse'
/var/vcap/data/packages/cf-mysql-broker/cd3a16e99fe291ce91fffe8af81f26d457829bd5-43b20ed10dce4af2eefb8431c390addb046b27e4/app/models/cloud_controller_http_client.rb:16:in `get'
/var/vcap/data/packages/cf-mysql-broker/cd3a16e99fe291ce91fffe8af81f26d457829bd5-43b20ed10dce4af2eefb8431c390addb046b27e4/lib/configuration.rb:28:in `cc_api_info'
/var/vcap/data/packages/cf-mysql-broker/cd3a16e99fe291ce91fffe8af81f26d457829bd5-43b20ed10dce4af2eefb8431c390addb046b27e4/lib/configuration.rb:17:in `auth_server_url'
/var/vcap/data/packages/cf-mysql-broker/cd3a16e99fe291ce91fffe8af81f26d457829bd5-43b20ed10dce4af2eefb8431c390addb046b27e4/config/initializers/omniauth.rb:10:in `block in <top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:6:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in `new'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `inject'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/engine.rb:495:in `app'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `instance_exec'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:215:in `initialize!'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/vcap/data/packages/cf-mysql-broker/cd3a16e99fe291ce91fffe8af81f26d457829bd5-43b20ed10dce4af2eefb8431c390addb046b27e4/config/environment.rb:5:in `<top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:189:in `require_environment!'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:260:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
Migrations failed at Mon Feb 22 21:27:58 UTC 2016```
``````

**Comment by sclevine** [comment]
Hi @geoffwa,

Are you still experiencing this issue with [the latest version (0.13.0) of PCF Dev](https://network.pivotal.io/products/pcfdev)?

**Comment by sclevine** [comment]
Closing due to inactivity. Feel free to re-open if you're still experiencing this issue.

**Comment by zhoutiekui** [comment]
rake aborted!
SocketError: getaddrinfo: Name or service not known
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/app/models/cloud_controller_http_client.rb:14:in 

`get'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/lib/configuration.rb:28:in`cc_api_info'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/lib/configuration.rb:17:in `auth_server_url'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/config/initializers/omniauth.rb:10:in`block in <top 

(required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in`initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:6:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in`new'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in`block in build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in`inject'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/engine.rb:495:in`app'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in`instance_exec'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:55:in`block in run_initializers'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:215:in`initialize!'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/config/environment.rb:5:in`<top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in`block in require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in`require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:189:in `require_environment!'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:260:in`block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
Migrations failed at Fri Jul 29 09:36:04 UTC 2016
mysql_broker already exists
rake aborted!
SocketError: getaddrinfo: Name or service not known
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/app/models/cloud_controller_http_client.rb:14:in 

`get'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/lib/configuration.rb:28:in`cc_api_info'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/lib/configuration.rb:17:in `auth_server_url'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/config/initializers/omniauth.rb:10:in`block in <top 

(required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in`initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:6:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in`new'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in`block in build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in`inject'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/

**Comment by zhoutiekui** [comment]
i hava encouter the same error, is there any solution?
i use cf-mysql-release v26 

rake aborted!
SocketError: getaddrinfo: Name or service not known
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/app/models/cloud_controller_http_client.rb:14:in 

`get'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/lib/configuration.rb:28:in`cc_api_info'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/lib/configuration.rb:17:in `auth_server_url'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/config/initializers/omniauth.rb:10:in`block in <top 

(required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in`initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:6:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in`new'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in`block in build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in`inject'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/engine.rb:495:in`app'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in`instance_exec'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:55:in`block in run_initializers'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:215:in`initialize!'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/config/environment.rb:5:in`<top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in`block in require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in`require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:189:in `require_environment!'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:260:in`block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
Migrations failed at Fri Jul 29 09:36:04 UTC 2016
mysql_broker already exists
rake aborted!
SocketError: getaddrinfo: Name or service not known
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/app/models/cloud_controller_http_client.rb:14:in 

`get'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/lib/configuration.rb:28:in`cc_api_info'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/lib/configuration.rb:17:in `auth_server_url'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-6d06770c0c7b0f192aa9c1a49762227b76034aa5/config/initializers/omniauth.rb:10:in`block in <top 

(required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in`initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:6:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in`new'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in`block in build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in`inject'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/

**Comment by sclevine** [comment]
This is the issue tracker for PCF Dev, a local version of PCF that comes with cf-mysql-release pre-installed. Your issue does not seem related to the opening issue, which was resolved.
